site_name: Vision Learner
site_description: Learning projects in Computer Vision

repo_url: https://github.com/HangenYuu/vision_learner
repo_name: HangenYuu/vision_learner

theme:
  name: mkdocs
  highlightjs: true
  palette:
    primary: black

plugins:
 - mkdocs-jupyter:
    include_source: True
 - search

nav:
  - Home: 'index.md'
  - About: 'about.md'